### ISSUE TITLE
Broken link for "live installation" mentioned in 'docs/typediff.md'

### ISSUE THREAD

**Issue by glenn-slayden** [ned2/typediff#1]
Broken link:

https://github.com/ned2/typediff/blob/f226a2d9b035d80a5a987becd546ad994df896a6/docs/typediff.md#L11-L12

<br>
<br>

![typediff-timeout](https://user-images.githubusercontent.com/5589855/38054305-687d4bc2-328b-11e8-8a52-e1cb7d577d8b.png)

**Comment by goodmami** [comment]
Actually I think the whole csse.unimelb.edu.au domain is currently down. The UM servers for delphin-viz are also unresponsive.

**Comment by ned2** [comment]
Ah yes, sorry about that. That machine has been decommissioned. Unfortunately I'm still waiting to get my the new machine up and running. I've removed the dead link and will update with a new one when it comes online. Also note that the installation instructions are also out of date. I'll try and fix that in the next few days. 

Thanks for reporting!
